// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickLogistics.Data;

#nullable disable

namespace QuickLogistics.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240822093444_AddDriverIdToDB")]
    partial class AddDriverIdToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuickLogistics.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            DriverId = 1,
                            Address = "Iyanapaja, Lagos",
                            LicenseNumber = "D12345",
                            Name = "Adefemi Adedayo",
                            PhoneNumber = "09043289743"
                        },
                        new
                        {
                            DriverId = 2,
                            Address = "Yaba, Lagos",
                            LicenseNumber = "D67890",
                            Name = "Azeez Babalola",
                            PhoneNumber = "08103289243"
                        },
                        new
                        {
                            DriverId = 3,
                            Address = "Oniru, Lagos",
                            LicenseNumber = "B47630",
                            Name = "Uche Phillips",
                            PhoneNumber = "08071289463"
                        });
                });

            modelBuilder.Entity("QuickLogistics.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            LicensePlate = "ABC123",
                            Model = "Truck"
                        },
                        new
                        {
                            VehicleId = 2,
                            LicensePlate = "XYZ789",
                            Model = "Van"
                        },
                        new
                        {
                            VehicleId = 3,
                            LicensePlate = "DES439",
                            Model = "Bajaj"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
