// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickLogistics.Data;

#nullable disable

namespace QuickLogistics.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240822122147_SeedAndModelCollectionFromVehicleAndDriverToDB")]
    partial class SeedAndModelCollectionFromVehicleAndDriverToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuickLogistics.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            DriverId = 1,
                            Address = "Iyanapaja, Lagos",
                            LicenseNumber = "D12345",
                            Name = "Adefemi Adedayo",
                            PhoneNumber = "09043289743"
                        },
                        new
                        {
                            DriverId = 2,
                            Address = "Yaba, Lagos",
                            LicenseNumber = "D67890",
                            Name = "Azeez Babalola",
                            PhoneNumber = "08103289243"
                        },
                        new
                        {
                            DriverId = 3,
                            Address = "Oniru, Lagos",
                            LicenseNumber = "B47630",
                            Name = "Uche Phillips",
                            PhoneNumber = "08071289463"
                        });
                });

            modelBuilder.Entity("QuickLogistics.Models.Shipment", b =>
                {
                    b.Property<int>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipmentId"));

                    b.Property<DateTime?>("DeliveredDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("ShipmentId");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Shipments");

                    b.HasData(
                        new
                        {
                            ShipmentId = 1,
                            DeliveredDate = new DateTime(2024, 8, 21, 5, 21, 46, 933, DateTimeKind.Local).AddTicks(5479),
                            DriverId = 1,
                            ShippedDate = new DateTime(2024, 8, 17, 5, 21, 46, 933, DateTimeKind.Local).AddTicks(5394),
                            TrackingNumber = "SHIP001",
                            VehicleId = 1
                        },
                        new
                        {
                            ShipmentId = 2,
                            DeliveredDate = new DateTime(2024, 8, 20, 5, 21, 46, 933, DateTimeKind.Local).AddTicks(5498),
                            DriverId = 2,
                            ShippedDate = new DateTime(2024, 8, 15, 5, 21, 46, 933, DateTimeKind.Local).AddTicks(5494),
                            TrackingNumber = "SHIP002",
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("QuickLogistics.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            LicensePlate = "ABC123",
                            Model = "Truck"
                        },
                        new
                        {
                            VehicleId = 2,
                            LicensePlate = "XYZ789",
                            Model = "Van"
                        },
                        new
                        {
                            VehicleId = 3,
                            LicensePlate = "DES439",
                            Model = "Bajaj"
                        });
                });

            modelBuilder.Entity("QuickLogistics.Models.Shipment", b =>
                {
                    b.HasOne("QuickLogistics.Models.Driver", "Driver")
                        .WithMany("Shipments")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuickLogistics.Models.Vehicle", "Vehicle")
                        .WithMany("Shipments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("QuickLogistics.Models.Driver", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("QuickLogistics.Models.Vehicle", b =>
                {
                    b.Navigation("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
